"""Add website, seeking columns into Artist and Venue, create venue_genres relationship

Revision ID: 28d4390250b8
Revises: 84bab23c4d10
Create Date: 2023-07-30 11:20:59.851727

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28d4390250b8"
down_revision = "84bab23c4d10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "venue_genres",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["Genre.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["Venue.id"],
        ),
        sa.PrimaryKeyConstraint("venue_id", "genre_id"),
    )
    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.add_column(sa.Column("website", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("seeking_venue", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("seeking_description", sa.String(), nullable=True))

    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.add_column(sa.Column("website", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("seeking_talent", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("seeking_description", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.drop_column("seeking_description")
        batch_op.drop_column("seeking_talent")
        batch_op.drop_column("website")

    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.drop_column("seeking_description")
        batch_op.drop_column("seeking_venue")
        batch_op.drop_column("website")

    op.drop_table("venue_genres")
    # ### end Alembic commands ###
