"""Add time column

Revision ID: 2d08f838d55a
Revises: 8cebf7803a84
Create Date: 2023-08-04 06:12:18.550287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d08f838d55a'
down_revision = '8cebf7803a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
