"""Add Genre table

Revision ID: 84bab23c4d10
Revises: 543e778a3ec9
Create Date: 2023-07-29 15:25:37.994817

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "84bab23c4d10"
down_revision = "543e778a3ec9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Genre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "artist_genres",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["Artist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["Genre.id"],
        ),
        sa.PrimaryKeyConstraint("artist_id", "genre_id"),
    )
    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.drop_column("genres")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "genres", sa.VARCHAR(length=120), autoincrement=False, nullable=True
            )
        )

    op.drop_table("artist_genres")
    op.drop_table("Genre")
    # ### end Alembic commands ###
