"""Change nullable option

Revision ID: 8cebf7803a84
Revises: 936676e9d5ab
Create Date: 2023-08-02 23:13:14.759237

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8cebf7803a84"
down_revision = "936676e9d5ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.alter_column(
            "city", existing_type=sa.VARCHAR(length=120), nullable=False
        )
        batch_op.alter_column(
            "state", existing_type=sa.VARCHAR(length=120), nullable=False
        )

    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.alter_column(
            "city", existing_type=sa.VARCHAR(length=120), nullable=False
        )
        batch_op.alter_column(
            "state", existing_type=sa.VARCHAR(length=120), nullable=False
        )
        batch_op.alter_column(
            "address", existing_type=sa.VARCHAR(length=120), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.alter_column(
            "address", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.alter_column(
            "state", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.alter_column("city", existing_type=sa.VARCHAR(length=120), nullable=True)

    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.alter_column(
            "state", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.alter_column("city", existing_type=sa.VARCHAR(length=120), nullable=True)

    # ### end Alembic commands ###
