"""Add unique to genre's name

Revision ID: 936676e9d5ab
Revises: 439d329b3c25
Create Date: 2023-07-31 21:59:22.659236

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "936676e9d5ab"
down_revision = "439d329b3c25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Genre", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Genre", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
